In [2]:
import pandas as pd
import numpy as np

In [3]:
test_data = pd.read_csv("~/Desktop/flight_testing.csv")

In [ ]:
test_data.head()

In [5]:
test_data.groupby("origin").count()["fl_date"]

origin
ABE     95
ABI     39
ABQ    523
ABR     14
ABY     16
      ...
WRG     14
XNA    232
YAK     12
YKM     27
YUM     27
Name: fl_date, Length: 360, dtype: int64

In [6]:
test_data.groupby("origin").nunique()

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,...,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,no_name
origin,,,,,,,,,,,,,,,,,,,,,
ABE,7,4,5,4,23,7,82,23,1,1,...,9,9,2,8,2,8,1,1,1,1
ABI,7,1,1,1,8,1,25,8,1,1,...,1,8,9,13,2,8,2,2,2,1
ABQ,7,8,12,8,256,17,418,257,1,1,...,25,33,16,43,3,48,4,4,4,1
ABR,7,1,1,1,2,1,12,2,1,1,...,1,2,2,2,2,2,1,1,1,1
ABY,7,1,1,1,5,1,10,5,1,1,...,1,3,3,3,2,3,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WRG,7,1,1,1,2,1,6,2,1,1,...,2,4,3,5,2,3,1,1,1,1
XNA,7,4,6,4,66,12,175,67,1,1,...,14,13,4,21,3,16,3,3,3,1
YAK,6,1,1,1,2,1,9,2,1,1,...,2,2,2,3,2,3,1,1,1,1
YKM,7,1,1,1,6,1,19,6,1,1,...,1,2,2,4,2,2,1,1,1,1
YUM,7,1,1,1,4,1,14,4,1,1,...,1,2,2,4,2,5,1,1,1,1