In [5]:
import pandas as pd

In [6]:
df_train = pd.read_csv("~/Desktop/DataDump/Flights_Weather_TRAIN.csv", )

In [7]:
df_train.head()

,Unnamed: 0,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,...,dep_Storm,dep_Hail,dep_Precipitation,arr_Rain,arr_Fog,arr_Snow,arr_Cold,arr_Storm,arr_Hail,arr_Precipitation
0,0,2019-01-07,AA,AA_CODESHARE,AA,2989,OO,N744EV,2989,11049,...,NW,NW,NW,Light,NW,NW,NW,NW,NW,NW
1,1,2019-01-07,UA,UA_CODESHARE,UA,3827,ZW,N424AW,3827,13367,...,NW,NW,NW,Light,NW,NW,NW,NW,NW,NW
2,2,2019-01-07,DL,DL_CODESHARE,DL,3803,OO,N291SY,3803,13930,...,NW,NW,NW,NW,NW,NW,NW,NW,NW,NW
3,3,2019-01-07,DL,DL_CODESHARE,DL,3804,OO,N272SY,3804,13930,...,NW,NW,NW,NW,NW,NW,NW,NW,NW,NW
4,4,2019-01-07,DL,DL_CODESHARE,DL,3805,OO,N290SY,3805,11996,...,NW,NW,NW,NW,NW,NW,NW,NW,NW,NW